// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using game.Models;

namespace game.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20190830001047_FirstMigrations")]
    partial class FirstMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("game.Models.Characters", b =>
                {
                    b.Property<int>("CharId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Dexterity");

                    b.Property<int>("Energy");

                    b.Property<int>("Exp");

                    b.Property<int>("Health");

                    b.Property<int>("Level");

                    b.Property<int>("Points");

                    b.Property<int>("Strength");

                    b.Property<int>("UserId");

                    b.HasKey("CharId");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("game.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Archer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("pw");

                    b.Property<bool>("Samurai");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnName("user_name");

                    b.Property<bool>("Wizard");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("game.Models.Characters", b =>
                {
                    b.HasOne("game.Models.User", "myuser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
